"""add mitre technique to rules

Revision ID: d0fbb8700f1d
Revises: 072d157c3cab
Create Date: 2026-07-24 16:47:31.007627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0fbb8700f1d'
down_revision: Union[str, Sequence[str], None] = '072d157c3cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verdicts_id'), table_name='verdicts')
    op.drop_table('verdicts')
    op.add_column('rules', sa.Column('mitre_technique', sa.String(length=20), nullable=True))
    op.alter_column('verdict_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_verdict_events_rule_id'), table_name='verdict_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_verdict_events_rule_id'), 'verdict_events', ['rule_id'], unique=False)
    op.alter_column('verdict_events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('rules', 'mitre_technique')
    op.create_table('verdicts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rule_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('verdict', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('verdict_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('verdicts_pkey'))
    )
    op.create_index(op.f('ix_verdicts_id'), 'verdicts', ['id'], unique=False)
    # ### end Alembic commands ###
